Add update schema
CESARBR/knot-babeltower pull request #25
Opened 2019-12-11 20:00 UTC by joaoaneto

What does this implement/fix? Explain your changes
---------------------------------------------------
Adds update thing's schema capability.

Does this close any currently open issues?
------------------------------------------
Closes #2 

...

Any other comments\?
-------------------
Documentation is still missing.

Where has this been tested?
---------------------------

**Operating System/Platform:** macOS 10.14 - Darwin 18.0.0

**Go Version:** go1.12.7 darwin/amd64

2019-12-11 20:01 UTC, joaoaneto commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/thing/interactors/register_thing.go  6
- pkg/user/interactors/create_user.go  2
- pkg/thing/handler/amqp/msg_handler.go  8
- pkg/thing/delivery/amqp/msg_publisher.go  2
- pkg/thing/interactors/interactor.go  1
- pkg/thing/interactors/update_schema_test.go  3
- pkg/thing/interactors/update_schema.go  5
- pkg/user/interactors/create_user_test.go  4
- pkg/user/controllers/user.go  3
- pkg/user/delivery/http/user_proxy.go  4
- cmd/main.go  8
- pkg/thing/delivery/http/thing_proxy.go  4
- pkg/thing/interactors/register_thing_test.go  5
- pkg/thing/delivery/amqp/connector.go  2
- pkg/network/amqp.go  4
- pkg/entities/err_no_perm.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/joaoaneto/knot-babeltower/pullRequest?prid=4660884&bid=15606802)

2020-01-03 21:31 UTC, joaoaneto commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/thing/interactors/register_thing_test.go  5
- pkg/user/delivery/http/user_proxy.go  4
- cmd/main.go  8
- pkg/user/interactors/create_user_test.go  4
- pkg/thing/handler/amqp/msg_handler.go  8
- pkg/user/interactors/create_user.go  2
- pkg/thing/delivery/http/thing_proxy.go  5
- pkg/thing/delivery/amqp/msg_publisher.go  2
- pkg/thing/interactors/interactor.go  1
- pkg/user/controllers/user.go  3
- pkg/thing/interactors/update_schema_test.go  3
- pkg/thing/interactors/update_schema.go  8
- pkg/entities/err_no_perm.go  1
- pkg/thing/interactors/register_thing.go  6
- pkg/network/amqp.go  4
- pkg/thing/delivery/amqp/connector.go  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4660884&bid=15606802)

2020-01-07 18:44 UTC, joaoaneto commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/thing/interactors/update_schema_test.go  3
- pkg/user/interactors/create_user_test.go  4
- pkg/user/interactors/create_token_test.go  3
- pkg/thing/interactors/register_thing_test.go  5
- pkg/thing/interactors/update_schema.go  8
- pkg/user/interactors/create_user.go  2
- pkg/thing/delivery/amqp/connector.go  2
- pkg/user/delivery/http/user_proxy.go  5
- pkg/thing/delivery/http/thing_proxy.go  5
- pkg/thing/handler/amqp/msg_handler.go  7
- pkg/user/interactors/create_token.go  2
- pkg/thing/interactors/register_thing.go  6
- pkg/thing/interactors/interactor.go  1
- pkg/user/controllers/user.go  4
- pkg/thing/delivery/amqp/msg_publisher.go  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4660884&bid=15606802)

2020-01-15 22:33 UTC, joaoaneto commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/thing/interactors/update_schema_test.go  3
- pkg/thing/interactors/update_schema.go  8
- pkg/thing/handler/amqp/msg_handler.go  3
         

Complexity decreasing per file
==============================
+ pkg/thing/delivery/http/thing_proxy.go  -2
         

Clones added
============
- pkg/thing/interactors/update_schema_test.go  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4660884&bid=15606802)

2020-01-16 14:18 UTC, joaoaneto commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/thing/handler/amqp/msg_handler.go  3
- pkg/thing/interactors/update_schema_test.go  3
- pkg/thing/interactors/update_schema.go  8
         

Complexity decreasing per file
==============================
+ pkg/thing/delivery/http/thing_proxy.go  -2
         

Clones added
============
- pkg/thing/interactors/update_schema_test.go  6
- pkg/thing/interactors/register_thing_test.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4660884&bid=15606802)

2020-01-16 19:07 UTC, joaoaneto commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/thing/interactors/update_schema.go  8
- pkg/thing/handler/amqp/msg_handler.go  3
- pkg/thing/interactors/update_schema_test.go  3
         

Complexity decreasing per file
==============================
+ pkg/thing/delivery/http/thing_proxy.go  -2
         

Clones added
============
- pkg/thing/interactors/register_thing_test.go  1
- pkg/thing/interactors/update_schema_test.go  11
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4660884&bid=15606802)

2020-01-20 15:07 UTC, vitbaq requested changes

2020-01-20 15:07 UTC, vitbaq commented on pkg/thing/handler/amqp/msg_handler.go
> +type UpdateSchemaRequest struct {
This struct can be located at knot-babeltower/pkg/network/msg.go

2020-01-20 15:07 UTC, vitbaq commented on pkg/thing/delivery/amqp/msg_publisher.go
> +type UpdatedSchemaResponse struct {
This struct can be located at knot-babeltower/pkg/network/msg.go

2020-01-20 15:07 UTC, vitbaq commented on pkg/thing/delivery/http/thing_proxy.go
> +func (p proxy) mapErrorFromStausCode(code int) error {
Typo? StatusCode

2020-01-21 14:33 UTC, vitbaq requested changes

2020-01-21 14:33 UTC, vitbaq commented on pkg/thing/handler/amqp/msg_handler.go
> +			authorizationHeader := msg.Headers["Authorization"]
Already done on line 89

2020-01-21 14:33 UTC, vitbaq commented on pkg/thing/handler/amqp/msg_handler.go
> +			err = mc.thingInteractor.UpdateSchema(authorizationHeader.(string), updateSchemaReq.ID, updateSchemaReq.Schema)
Create function handleUpdateSchemaMsg. Like handleRegisterMsg().

2020-01-21 20:10 UTC, joaoaneto commented on pkg/thing/handler/amqp/msg_handler.go
> +type UpdateSchemaRequest struct {
Actually, I was thinking about moving `RegisterRequestMsg` and `RegisterResponseMsg` to where they are used and remove that file. At least if the message is used by two files in different packages, it's better to define them where they are used. What do you think?

2020-01-21 20:42 UTC, joaoaneto commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/thing/handler/amqp/msg_handler.go  2
- pkg/thing/interactors/update_schema.go  8
- pkg/thing/interactors/update_schema_test.go  3
         

Complexity decreasing per file
==============================
+ pkg/thing/delivery/http/thing_proxy.go  -2
         

Clones added
============
- pkg/thing/interactors/register_thing_test.go  1
- pkg/thing/interactors/update_schema_test.go  11
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4660884&bid=15606802)

2020-01-21 20:45 UTC, joaoaneto commented on pkg/thing/handler/amqp/msg_handler.go
> +			err = mc.thingInteractor.UpdateSchema(authorizationHeader.(string), updateSchemaReq.ID, updateSchemaReq.Schema)
Done.

2020-01-21 20:46 UTC, joaoaneto commented on pkg/thing/handler/amqp/msg_handler.go
> +			authorizationHeader := msg.Headers["Authorization"]
Ack. Done.

2020-01-21 20:46 UTC, joaoaneto commented on pkg/thing/delivery/http/thing_proxy.go
> +func (p proxy) mapErrorFromStausCode(code int) error {
Yep, thanks. Done!

2020-01-21 20:46 UTC, joaoaneto commented on pkg/thing/delivery/amqp/msg_publisher.go
> +type UpdatedSchemaResponse struct {
Done!

2020-01-21 20:46 UTC, joaoaneto commented on pkg/thing/handler/amqp/msg_handler.go
> +type UpdateSchemaRequest struct {
Done!

2020-01-22 14:12 UTC, joaoaneto commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/thing/interactors/update_schema_test.go  3
- pkg/thing/interactors/update_schema.go  8
- pkg/thing/handler/amqp/msg_handler.go  2
         

Complexity decreasing per file
==============================
+ pkg/thing/delivery/http/thing_proxy.go  -2
         

Clones added
============
- pkg/thing/interactors/update_schema_test.go  11
- pkg/thing/interactors/register_thing_test.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4660884&bid=15606802)

2020-01-22 14:24 UTC, joaoaneto commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/thing/interactors/update_schema.go  8
- pkg/thing/handler/amqp/msg_handler.go  2
- pkg/thing/interactors/update_schema_test.go  3
         

Complexity decreasing per file
==============================
+ pkg/thing/delivery/http/thing_proxy.go  -2
         

Clones added
============
- pkg/thing/interactors/register_thing_test.go  1
- pkg/thing/interactors/update_schema_test.go  11
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4660884&bid=15606802)

2020-01-22 14:55 UTC, joaoaneto commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/thing/interactors/update_schema.go  8
- pkg/thing/handler/amqp/msg_handler.go  2
- pkg/thing/interactors/update_schema_test.go  3
         

Complexity decreasing per file
==============================
+ pkg/thing/delivery/http/thing_proxy.go  -2
         

Clones added
============
- pkg/thing/interactors/register_thing_test.go  1
- pkg/thing/interactors/update_schema_test.go  11
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4660884&bid=15606802)

2020-01-22 19:24 UTC, joaoaneto commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/thing/interactors/update_schema_test.go  3
- pkg/thing/interactors/update_schema.go  8
- pkg/thing/handler/amqp/msg_handler.go  2
         

Complexity decreasing per file
==============================
+ pkg/thing/delivery/http/thing_proxy.go  -2
         

Clones added
============
- pkg/thing/interactors/register_thing_test.go  1
- pkg/thing/interactors/update_schema_test.go  11
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4660884&bid=15606802)

2020-01-23 13:09 UTC, vitbaq approved these changes

2020-01-23 13:09 UTC, merged