Add list devices
CESARBR/knot-babeltower pull request #34
Opened 2020-01-20 20:08 UTC by joaoaneto

What does this implement/fix?
---------------------------------------------------
This patch adds list things command capability.

Does this close any currently open issues?
------------------------------------------
Closes #3

2020-01-20 20:10 UTC, joaoaneto commented on pkg/thing/mocks/thing_proxy.go
> +type FakeThingProxy struct {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported type FakeThingProxy should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 20:10 UTC, joaoaneto commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 19
           

Complexity increasing per file
==============================
- pkg/thing/interactors/list_things.go  4
- pkg/thing/mocks/publisher.go  1
- pkg/thing/mocks/thing_proxy.go  1
- pkg/thing/interactors/update_schema_test.go  3
- pkg/thing/mocks/logger.go  1
- pkg/thing/interactors/update_schema.go  8
- pkg/thing/handler/amqp/msg_handler.go  5
- pkg/thing/interactors/list_things_test.go  5
- pkg/thing/mocks/connector.go  1
         

Complexity decreasing per file
==============================
+ pkg/thing/delivery/http/thing_proxy.go  -2
         

Clones added
============
- pkg/thing/interactors/update_schema_test.go  13
- pkg/thing/interactors/list_things_test.go  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780&bid=16102946)

2020-01-20 20:10 UTC, joaoaneto commented on pkg/thing/mocks/publisher.go
> +type FakePublisher struct {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported type FakePublisher should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 20:10 UTC, joaoaneto commented on pkg/thing/mocks/logger.go
> +func (fl *FakeLogger) Errorf(string, ...interface{}) {}
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeLogger.Errorf should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 20:10 UTC, joaoaneto commented on pkg/thing/mocks/publisher.go
> +func (fp *FakePublisher) SendThings(things []*entities.Thing) error {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakePublisher.SendThings should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 20:10 UTC, joaoaneto commented on pkg/thing/mocks/logger.go
> +type FakeLogger struct{}
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported type FakeLogger should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 20:10 UTC, joaoaneto commented on pkg/thing/mocks/logger.go
> +func (fl *FakeLogger) Debug(...interface{}) {}
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeLogger.Debug should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 20:10 UTC, joaoaneto commented on pkg/thing/mocks/connector.go
> +func (fc *FakeConnector) SendUpdateSchema(id string, schemaList []entities.Schema) (err error) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeConnector.SendUpdateSchema should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 20:10 UTC, joaoaneto commented on pkg/thing/mocks/connector.go
> +func (fc *FakeConnector) SendRegisterDevice(id, name string) (err error) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeConnector.SendRegisterDevice should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 20:10 UTC, joaoaneto commented on pkg/thing/mocks/logger.go
> +func (fl *FakeLogger) Warn(...interface{}) {}
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeLogger.Warn should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 20:10 UTC, joaoaneto commented on pkg/thing/mocks/logger.go
> +func (fl *FakeLogger) Info(...interface{}) {}
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeLogger.Info should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 20:10 UTC, joaoaneto commented on pkg/thing/mocks/publisher.go
> +func (fp *FakePublisher) SendUpdatedSchema(thingID string) error {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakePublisher.SendUpdatedSchema should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 20:10 UTC, joaoaneto commented on pkg/thing/mocks/thing_proxy.go
> +func (ftp *FakeThingProxy) Get(authorization, thingID string) (*http.ThingProxyRepr, error) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeThingProxy.Get should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 20:10 UTC, joaoaneto commented on pkg/thing/mocks/publisher.go
> +func (fp *FakePublisher) SendRegisterDevice(msg network.RegisterResponseMsg) error {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakePublisher.SendRegisterDevice should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 20:10 UTC, joaoaneto commented on pkg/thing/mocks/logger.go
> +func (fl *FakeLogger) Infof(string, ...interface{}) {}
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeLogger.Infof should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 20:10 UTC, joaoaneto commented on pkg/thing/mocks/thing_proxy.go
> +func (ftp *FakeThingProxy) List(authorization string) ([]*entities.Thing, error) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeThingProxy.List should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 20:10 UTC, joaoaneto commented on pkg/thing/mocks/connector.go
> +type FakeConnector struct {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported type FakeConnector should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 20:10 UTC, joaoaneto commented on pkg/thing/mocks/connector.go
> +func (fc *FakeConnector) RecvRegisterDevice() (bytes []byte, err error) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeConnector.RecvRegisterDevice should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 20:10 UTC, joaoaneto commented on pkg/thing/mocks/thing_proxy.go
> +func (ftp *FakeThingProxy) Create(id, name, authorization string) (idGenerated string, err error) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeThingProxy.Create should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 20:10 UTC, joaoaneto commented on pkg/thing/mocks/thing_proxy.go
> +func (ftp *FakeThingProxy) UpdateSchema(authorization, thingID string, schema []entities.Schema) error {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeThingProxy.UpdateSchema should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 21:46 UTC, joaoaneto commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 19
           

Complexity increasing per file
==============================
- pkg/thing/mocks/logger.go  1
- pkg/thing/interactors/list_things_test.go  5
- pkg/thing/mocks/connector.go  1
- pkg/thing/interactors/update_schema_test.go  3
- pkg/thing/handler/amqp/msg_handler.go  5
- pkg/thing/mocks/publisher.go  1
- pkg/thing/interactors/update_schema.go  8
- pkg/thing/interactors/list_things.go  4
- pkg/thing/mocks/thing_proxy.go  1
         

Complexity decreasing per file
==============================
+ pkg/thing/delivery/http/thing_proxy.go  -2
         

Clones added
============
- pkg/thing/interactors/list_things_test.go  2
- pkg/thing/interactors/update_schema_test.go  13
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780&bid=16102946)

2020-01-20 21:46 UTC, joaoaneto commented on pkg/thing/mocks/thing_proxy.go
> +func (ftp *FakeThingProxy) List(authorization string) ([]*entities.Thing, error) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeThingProxy.List should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 21:46 UTC, joaoaneto commented on pkg/thing/mocks/logger.go
> +func (fl *FakeLogger) Debug(...interface{}) {}
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeLogger.Debug should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 21:46 UTC, joaoaneto commented on pkg/thing/mocks/connector.go
> +func (fc *FakeConnector) SendUpdateSchema(id string, schemaList []entities.Schema) (err error) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeConnector.SendUpdateSchema should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 21:46 UTC, joaoaneto commented on pkg/thing/mocks/logger.go
> +func (fl *FakeLogger) Infof(string, ...interface{}) {}
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeLogger.Infof should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 21:46 UTC, joaoaneto commented on pkg/thing/mocks/publisher.go
> +func (fp *FakePublisher) SendUpdatedSchema(thingID string) error {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakePublisher.SendUpdatedSchema should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 21:46 UTC, joaoaneto commented on pkg/thing/mocks/logger.go
> +func (fl *FakeLogger) Info(...interface{}) {}
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeLogger.Info should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 21:46 UTC, joaoaneto commented on pkg/thing/mocks/publisher.go
> +func (fp *FakePublisher) SendThings(things []*entities.Thing) error {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakePublisher.SendThings should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 21:46 UTC, joaoaneto commented on pkg/thing/mocks/logger.go
> +type FakeLogger struct{}
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported type FakeLogger should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 21:46 UTC, joaoaneto commented on pkg/thing/mocks/connector.go
> +func (fc *FakeConnector) RecvRegisterDevice() (bytes []byte, err error) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeConnector.RecvRegisterDevice should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 21:46 UTC, joaoaneto commented on pkg/thing/mocks/logger.go
> +func (fl *FakeLogger) Errorf(string, ...interface{}) {}
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeLogger.Errorf should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 21:46 UTC, joaoaneto commented on pkg/thing/mocks/publisher.go
> +type FakePublisher struct {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported type FakePublisher should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 21:46 UTC, joaoaneto commented on pkg/thing/mocks/thing_proxy.go
> +func (ftp *FakeThingProxy) Get(authorization, thingID string) (*http.ThingProxyRepr, error) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeThingProxy.Get should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 21:46 UTC, joaoaneto commented on pkg/thing/mocks/logger.go
> +func (fl *FakeLogger) Warn(...interface{}) {}
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeLogger.Warn should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 21:46 UTC, joaoaneto commented on pkg/thing/mocks/thing_proxy.go
> +type FakeThingProxy struct {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported type FakeThingProxy should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 21:46 UTC, joaoaneto commented on pkg/thing/mocks/connector.go
> +func (fc *FakeConnector) SendRegisterDevice(id, name string) (err error) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeConnector.SendRegisterDevice should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 21:46 UTC, joaoaneto commented on pkg/thing/mocks/thing_proxy.go
> +func (ftp *FakeThingProxy) UpdateSchema(authorization, thingID string, schema []entities.Schema) error {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeThingProxy.UpdateSchema should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 21:46 UTC, joaoaneto commented on pkg/thing/mocks/connector.go
> +type FakeConnector struct {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported type FakeConnector should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 21:46 UTC, joaoaneto commented on pkg/thing/mocks/publisher.go
> +func (fp *FakePublisher) SendRegisterDevice(msg network.RegisterResponseMsg) error {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakePublisher.SendRegisterDevice should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-20 21:46 UTC, joaoaneto commented on pkg/thing/mocks/thing_proxy.go
> +func (ftp *FakeThingProxy) Create(id, name, authorization string) (idGenerated string, err error) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeThingProxy.Create should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-22 21:03 UTC, joaoaneto commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 19
           

Complexity increasing per file
==============================
- pkg/thing/interactors/list_things_test.go  5
- pkg/thing/mocks/connector.go  1
- pkg/thing/mocks/thing_proxy.go  1
- pkg/thing/interactors/update_schema_test.go  3
- pkg/thing/interactors/list_things.go  4
- pkg/thing/mocks/publisher.go  1
- pkg/thing/handler/amqp/msg_handler.go  4
- pkg/thing/mocks/logger.go  1
- pkg/thing/interactors/update_schema.go  8
         

Complexity decreasing per file
==============================
+ pkg/thing/delivery/http/thing_proxy.go  -2
         

Clones added
============
- pkg/thing/interactors/list_things_test.go  2
- pkg/thing/interactors/update_schema_test.go  13
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780&bid=16102946)

2020-01-22 21:03 UTC, joaoaneto commented on pkg/thing/mocks/publisher.go
> +func (fp *FakePublisher) SendRegisterDevice(msg network.RegisterResponseMsg) error {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakePublisher.SendRegisterDevice should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-22 21:03 UTC, joaoaneto commented on pkg/thing/mocks/publisher.go
> +func (fp *FakePublisher) SendThings(things []*entities.Thing) error {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakePublisher.SendThings should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-22 21:03 UTC, joaoaneto commented on pkg/thing/mocks/logger.go
> +func (fl *FakeLogger) Infof(string, ...interface{}) {}
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeLogger.Infof should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-22 21:03 UTC, joaoaneto commented on pkg/thing/mocks/connector.go
> +func (fc *FakeConnector) SendRegisterDevice(id, name string) (err error) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeConnector.SendRegisterDevice should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-22 21:03 UTC, joaoaneto commented on pkg/thing/mocks/publisher.go
> +type FakePublisher struct {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported type FakePublisher should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-22 21:03 UTC, joaoaneto commented on pkg/thing/mocks/logger.go
> +func (fl *FakeLogger) Info(...interface{}) {}
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeLogger.Info should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-22 21:03 UTC, joaoaneto commented on pkg/thing/mocks/logger.go
> +func (fl *FakeLogger) Debug(...interface{}) {}
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeLogger.Debug should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-22 21:03 UTC, joaoaneto commented on pkg/thing/mocks/logger.go
> +func (fl *FakeLogger) Errorf(string, ...interface{}) {}
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeLogger.Errorf should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-22 21:03 UTC, joaoaneto commented on pkg/thing/mocks/thing_proxy.go
> +func (ftp *FakeThingProxy) Get(authorization, thingID string) (*http.ThingProxyRepr, error) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeThingProxy.Get should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-22 21:03 UTC, joaoaneto commented on pkg/thing/mocks/thing_proxy.go
> +func (ftp *FakeThingProxy) Create(id, name, authorization string) (idGenerated string, err error) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeThingProxy.Create should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-22 21:03 UTC, joaoaneto commented on pkg/thing/mocks/thing_proxy.go
> +func (ftp *FakeThingProxy) UpdateSchema(authorization, thingID string, schema []entities.Schema) error {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeThingProxy.UpdateSchema should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-22 21:03 UTC, joaoaneto commented on pkg/thing/mocks/logger.go
> +func (fl *FakeLogger) Warn(...interface{}) {}
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeLogger.Warn should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-22 21:03 UTC, joaoaneto commented on pkg/thing/mocks/connector.go
> +type FakeConnector struct {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported type FakeConnector should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-22 21:03 UTC, joaoaneto commented on pkg/thing/mocks/connector.go
> +func (fc *FakeConnector) RecvRegisterDevice() (bytes []byte, err error) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeConnector.RecvRegisterDevice should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-22 21:03 UTC, joaoaneto commented on pkg/thing/mocks/thing_proxy.go
> +func (ftp *FakeThingProxy) List(authorization string) ([]*entities.Thing, error) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeThingProxy.List should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-22 21:03 UTC, joaoaneto commented on pkg/thing/mocks/thing_proxy.go
> +type FakeThingProxy struct {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported type FakeThingProxy should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-22 21:03 UTC, joaoaneto commented on pkg/thing/mocks/connector.go
> +func (fc *FakeConnector) SendUpdateSchema(id string, schemaList []entities.Schema) (err error) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakeConnector.SendUpdateSchema should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-22 21:03 UTC, joaoaneto commented on pkg/thing/mocks/publisher.go
> +func (fp *FakePublisher) SendUpdatedSchema(thingID string) error {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported method FakePublisher.SendUpdatedSchema should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-22 21:03 UTC, joaoaneto commented on pkg/thing/mocks/logger.go
> +type FakeLogger struct{}
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [exported type FakeLogger should have comment or be unexported](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780)

2020-01-23 13:29 UTC, joaoaneto commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/thing/handler/amqp/msg_handler.go  2
- pkg/thing/mocks/publisher.go  1
- pkg/thing/interactors/list_things_test.go  5
- pkg/thing/mocks/connector.go  1
- pkg/thing/interactors/list_things.go  4
- pkg/thing/mocks/thing_proxy.go  1
- pkg/thing/mocks/logger.go  1
         

Clones added
============
- pkg/thing/interactors/list_things_test.go  2
- pkg/thing/interactors/update_schema_test.go  2
         

Clones removed
==============
+ pkg/thing/interactors/register_thing_test.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4853780&bid=16102946)

2020-01-23 21:48 UTC, ramonhpr requested changes

2020-01-23 21:48 UTC, ramonhpr commented on pkg/thing/delivery/http/thing_proxy.go
> +	for i := range pagThings {
```suggestion
	for _, t := range pagThings {
```

2020-01-23 21:48 UTC, ramonhpr commented on pkg/thing/delivery/http/thing_proxy.go
> +		t := pagThings[i]
```suggestion
```

2020-01-24 12:25 UTC, joaoaneto commented on pkg/thing/delivery/http/thing_proxy.go
> +	for i := range pagThings {
Done. Thanks!

2020-01-24 12:25 UTC, joaoaneto commented on pkg/thing/delivery/http/thing_proxy.go
> +		t := pagThings[i]
Done. Thanks!

2020-01-27 19:46 UTC, ramonhpr approved these changes

2020-01-27 19:47 UTC, merged