Add device authentication operation
CESARBR/knot-babeltower pull request #40
Opened 2020-02-17 15:04 UTC by esdrasjnr

What does this implement/fix? Explain your changes
---------------------------------------------------
This patch implements the device auth command operation in the client side.

Where has this been tested?
---------------------------

**Operating System/Platform:** Ubuntu 18.04.4

**Go Version:** 1.13.6

2020-02-17 15:06 UTC, joaoaneto commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/thing/entities/err_thing_forbidden.go  1
- pkg/thing/delivery/amqp/client.go  2
- pkg/thing/interactors/auth_thing.go  6
- pkg/thing/handler/amqp/msg_handler.go  3
- pkg/thing/interactors/auth_thing_test.go  5
- pkg/thing/entities/err_thing_not_found.go  1
         

Complexity decreasing per file
==============================
+ pkg/thing/interactors/register_thing.go  -1
         

Clones added
============
- pkg/thing/interactors/auth_thing_test.go  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=5017969&bid=16543340)

2020-02-17 15:51 UTC, joaoaneto commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/thing/entities/err_thing_forbidden.go  1
- pkg/thing/interactors/auth_thing.go  6
- pkg/thing/entities/err_thing_not_found.go  1
- pkg/thing/handler/amqp/msg_handler.go  2
- pkg/thing/interactors/auth_thing_test.go  5
         

Clones added
============
- pkg/thing/interactors/auth_thing_test.go  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=5017969&bid=16543340)

2020-02-18 12:12 UTC, vitbaq requested changes

2020-02-18 12:12 UTC, vitbaq commented on pkg/thing/handler/amqp/msg_handler.go
> +func (mc *MsgHandler) handleAuthThing(body []byte, authorization string) error {
Change to handleAuthDevices

2020-02-18 20:48 UTC, joaoaneto commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/thing/handler/amqp/msg_handler.go  2
- pkg/thing/interactors/auth_thing.go  6
- pkg/thing/entities/err_thing_not_found.go  1
- pkg/thing/entities/err_thing_forbidden.go  1
- pkg/thing/interactors/auth_thing_test.go  5
         

Clones added
============
- pkg/thing/interactors/auth_thing_test.go  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=5017969&bid=16543340)

2020-02-18 20:49 UTC, esdrasjnr commented on pkg/thing/handler/amqp/msg_handler.go
> +func (mc *MsgHandler) handleAuthThing(body []byte, authorization string) error {
Done!

2020-02-27 15:01 UTC, joaoaneto commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/thing/entities/err_thing_not_found.go  1
- pkg/thing/interactors/auth_thing.go  6
- pkg/thing/interactors/auth_thing_test.go  5
- pkg/thing/handler/amqp/msg_handler.go  2
- pkg/thing/entities/err_thing_forbidden.go  1
         

Clones added
============
- pkg/thing/interactors/auth_thing_test.go  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=5017969&bid=16543340)

2020-02-28 12:08 UTC, joaoaneto commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/thing/interactors/auth_thing.go  6
- pkg/thing/interactors/auth_thing_test.go  5
- pkg/thing/entities/err_thing_forbidden.go  1
- pkg/thing/handler/amqp/msg_handler.go  2
- pkg/thing/entities/err_thing_not_found.go  1
         

Clones added
============
- pkg/thing/interactors/auth_thing_test.go  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=5017969&bid=16543340)

2020-02-28 12:12 UTC, vitbaq approved these changes

2020-02-28 12:12 UTC, merged