fix: Update dockerfiles and use GOPROXY
CESARBR/knot-babeltower pull request #56
Opened 2020-03-24 22:52 UTC by lcbm

**Describe what this PR introduces:** 
(if necessary, link currently open issues with [special keywords](https://help.github.com/en/articles/closing-issues-using-keywords))

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug fix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [X] Build-related changes
- [ ] Other, please describe: 

**Does this PR introduce any breaking changes?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [X] Related issues are referenced in the PR (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [X] All tests are passing
- [X] New/updated tests are included

**Testing environment:**

- Operating System/Platform: Linux 5.5.11-arch1-1 x86_64
- Go version: go1.14.1 linux/amd64
- Docker version: 19.03.8-ce, build afacb8b7f0

If you have relevant logs, error output and etc, please attach them.

**Other information:**

N/A :confetti_ball:

2020-03-31 11:58 UTC, netoax requested changes
Excellent patch, @lcbm. Thanks!
Just one commit message to adjust:

_78f7dadc2858cf6847ee82d941eeca00bfd3292f_
The version isn't bumped in this commit.
"**In addition, bump golang-alpine to v1.14 in the
dockerfiles.** "

2020-03-31 19:33 UTC, lcbm commented
@joaoaneto, commit message updated :smile:

2020-03-31 21:10 UTC, netoax approved these changes

2020-04-01 16:39 UTC, esdrasjnr approved these changes
Excellent patch! LGTM, thanks :100:

2020-04-01 16:41 UTC, merged