Migrate auth and list operations to the new request-reply model
CESARBR/knot-babeltower pull request #66
Opened 2020-04-27 21:59 UTC by joaoaneto

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug fix
- [ ] Feature
- [ ] Code style update
- [X] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce any breaking changes?**

- [X] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

Authenticate and list devices operations are no longer supported through `topic` exchanges. In order to achieve compatibility again, the clients must send the request to a `direct` exchange and pass a correlation via headers. The command response should be received by listening to that `direct` exchange and filter by using the correlation ID as the new binding key.

**The PR fulfills these requirements:**

- [ ] Related issues are referenced in the PR (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [X] All tests are passing
- [X] New/updated tests are included

**Testing environment:**

- Operating System/Platform: MacOS - darwin/amd64
- Go version: 1.14

2020-04-29 22:01 UTC, lcbm requested changes
Awesome patch :heart_eyes: 

Made some remarks, all regarding identifier naming! Other than that, everything looks good to me :smile:

2020-04-29 22:01 UTC, lcbm commented on pkg/network/amqp.go
> +	err := a.declareExchange(exchangeName, kind)
What do you think about using the same naming convention across identifiers (`exchangeType` in favor of `kind`)?  Curiously, it seems [streadway](https://github.com/streadway/amqp/blob/master/_examples/simple-producer/producer.go#L17)  also uses this standard :smiley:

In addition, don't you think `queueName` seems redundant? Here's [another example from streadway](https://github.com/streadway/amqp/blob/master/_examples/simple-consumer/consumer.go). 

```suggestion
func (a *Amqp) OnMessage(msgChan chan InMsg, queue, exchangeName, exchangeType, key string) error {
	err := a.declareExchange(exchangeName, kind)
```

2020-04-29 22:01 UTC, lcbm commented on pkg/network/amqp.go
> +		nil,   // arguments
This might be a good opportunity to update this chunk of code! I've found that initializations without field names are a bad practice and field names should be used in favor of comments ([see Ubers' example](https://github.com/uber-go/guide/blob/master/style.md#use-field-names-to-initialize-structs)).

Keep in mind that this is a only a suggestion, tho!

2020-04-29 22:01 UTC, lcbm commented on pkg/server/handler.go
> +	subscribe(msgChan, queueNameFogIn, exchangeFogIn, "topic", bindingKeyDevice)
Could this be a `const`? :thinking:
This way, if it ever changes, we only need to update it in a single place. In addition, its mode readable for the developer.
 
Also, same as [here](https://github.com/CESARBR/knot-babeltower/pull/66#discussion_r417625667), regarding `queueName...`

```Go
const exchangeTypeFogIn = "topic"
```

```suggestion
	subscribe(msgChan, queueNameFogIn, exchangeFogIn, exchangeTypeFogIn, bindingKeyDevice)
```

2020-04-29 22:01 UTC, lcbm commented on pkg/server/handler.go
> +	subscribe(msgChan, queueNameCommands, exchangeDevices, "direct", bindingKeyListDevices)
Same as as [here](https://github.com/CESARBR/knot-babeltower/pull/66#discussion_r417632374): don't you think this could be a `const`?

2020-04-29 22:01 UTC, lcbm commented on pkg/server/handler.go
> +
Is this blank space necessary? hehe :stuck_out_tongue:

2020-04-29 22:13 UTC, esdrasjnr approved these changes
Excellent refactor, everything LGTM! Just comment about one point I've noticed. However I approve, since it's not relevant

2020-04-29 22:13 UTC, esdrasjnr commented on pkg/network/amqp.go
> +func (a *Amqp) declareExchange(name string, kind string) error {
`func (a * Amqp) declareExchange(name, kind string) {`
Why didn't you follow the standard declaration above?

2020-05-04 13:10 UTC, netoax commented on pkg/network/amqp.go
> +	err := a.declareExchange(exchangeName, kind)
Done, thanks!

[streadway](https://github.com/streadway/amqp/blob/55cd81a10b0c3b411968dfeb3cdd2adb4cb975a7/channel.go#L1140) uses `kind` as `channel.ExchangeDeclare()` parameter but I think your suggestion fits well in our code.

`queueName` doesn't seems redundant in general but as the function scope is small, I agree with your suggestion.

2020-05-04 13:12 UTC, netoax commented on pkg/network/amqp.go
> +		nil,   // arguments
Good suggestion but these are function arguments and not structure fields to be initialized. Unfortunately, at least until I know, there's no support to named arguments in golang as there's in Python (for example).

2020-05-04 13:12 UTC, netoax commented on pkg/server/handler.go
> +	subscribe(msgChan, queueNameFogIn, exchangeFogIn, "topic", bindingKeyDevice)
Done.

2020-05-04 13:12 UTC, netoax commented on pkg/server/handler.go
> +	subscribe(msgChan, queueNameCommands, exchangeDevices, "direct", bindingKeyListDevices)
Done.

2020-05-04 13:13 UTC, netoax commented on pkg/server/handler.go
> +
Nops. Done!

2020-05-04 13:13 UTC, netoax commented on pkg/network/amqp.go
> +func (a *Amqp) declareExchange(name string, kind string) error {
I didn't notice that, thanks!

2020-05-04 21:33 UTC, lcbm approved these changes
LGTM! 🎊

2020-05-05 12:48 UTC, merged