Migrate operations to new API
CESARBR/knot-babeltower pull request #67
Opened 2020-04-28 21:58 UTC by joaoaneto

**Describe what this PR introduces:** (if necessary, link currently open issues with [special keywords](https://help.github.com/en/articles/closing-issues-using-keywords))

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug fix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce any breaking changes?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] Related issues are referenced in the PR (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included

**Testing environment:**

- Operating System/Platform:
- Go version:

If you have relevant logs, error output and etc, please attach them.

**Other information:**

2020-04-30 01:18 UTC, lcbm requested changes
Awesome patch! :rocket: 

I made a few remarks, and I also notice some typos in the commit messages :point_down: 

- commit 09592e63b9d6187821560523c46d9fb91c314ddb: `compatilize` is actually `make compatible` (I made the same mistake, hehe. Apparently, `compatibility` is not a word!
- commit 327a6c525a96983034891d6d407a821cc98a6c67: same as above, regarding`compatibilize` and also `suport` is supposed to be `supported`.
- commit 2524866148e46a1ad188feef54e49415695dbbe1: `updateed` should be `updated`

2020-04-30 01:18 UTC, lcbm commented on pkg/server/handler.go
> +	subscribe(msgChan, queueNameCommands, exchangeDevices, "direct", bindingKeySchemaSent)
Same as [here](https://github.com/CESARBR/knot-babeltower/pull/66#discussion_r417625667), regarding `"direct"`. Maybe this should be a `const` :smile:

2020-04-30 01:18 UTC, lcbm commented on pkg/server/handler.go
> +
Same as the previous (also [here](https://github.com/CESARBR/knot-babeltower/pull/66#discussion_r417625667)), regarding `"fanout"`. Maybe this should be a `const` :smile:

2020-04-30 01:18 UTC, lcbm commented on pkg/thing/delivery/amqp/client.go
> +	return mp.amqp.PublishPersistentMessage("data.published", "fanout", "", msg)
Same as mentioned earlier, as an attempt to avoid hard-coded exchanges, topics, queues, etc.

2020-05-04 14:05 UTC, netoax commented on pkg/server/handler.go
> +	subscribe(msgChan, queueNameCommands, exchangeDevices, "direct", bindingKeySchemaSent)
Done.

2020-05-04 14:05 UTC, netoax commented on pkg/server/handler.go
> +
Done.

2020-05-04 14:05 UTC, netoax commented on pkg/thing/delivery/amqp/client.go
> +	return mp.amqp.PublishPersistentMessage("data.published", "fanout", "", msg)
Done.

2020-05-04 21:46 UTC, lcbm approved these changes
This is awesome, congrats! 🎊 🚀 💯 

I'm approving this in advance, but please don't forget to fix this 👇 😄 

These two identifiers are never used, but instead of deleting them we should add them to where their values are used...
- `updateDataOutKey` ("data.update"): add `updateDataOutKey` to **line 122**; 
- `requestDataOutKey` ("data.request"): add `requestDataOutKey` to **line 110**.

2020-05-05 13:01 UTC, netoax commented
> This is awesome, congrats! 🎊 🚀 💯
> 
> I'm approving this in advance, but please don't forget to fix this 👇 😄
> 
> These two identifiers are never used, but instead of deleting them we should add them to where their values are used...
> 
> * `updateDataOutKey` ("data.update"): add `updateDataOutKey` to **line 122**;
> * `requestDataOutKey` ("data.request"): add `requestDataOutKey` to **line 110**.

Are you suggesting rename the local `routingKey` variables to `updateDataOutKey ` and `requestDataOutKey ` or concatenate them to the new strings?

2020-05-05 18:03 UTC, netoax commented
@lcbm fixed.
- [requestDataOutKey](https://github.com/CESARBR/knot-babeltower/pull/67/commits/df984188eeee9f3c4e05f05d94ac6c7f7e3fabb8#diff-e0f5cd6a36757114487201738a4976e0R110)
- [updateDataOutKey](https://github.com/CESARBR/knot-babeltower/pull/67/commits/df984188eeee9f3c4e05f05d94ac6c7f7e3fabb8#diff-e0f5cd6a36757114487201738a4976e0R122)
- 2b9885cacff7ad80a04f480850d271a3284c6497

2020-05-05 19:48 UTC, lcbm approved these changes
LGTM! :smile:

2020-05-06 15:15 UTC, esdrasjnr approved these changes
Everything LGTM! Awesome patch!

2020-05-06 15:58 UTC, ramonhpr reviewed
LGTM, just see my suggestion about binding key

2020-05-06 15:58 UTC, ramonhpr commented on pkg/server/handler.go
> +	subscribe(msgChan, queueNameEvents, exchangeDataSent, exchangeDataSentType, "")
```suggestion
	subscribe(msgChan, queueNameEvents, exchangeDataSent, exchangeDataSentType, bindKeyAny)
```
Add other const value

2020-05-06 15:58 UTC, ramonhpr commented on pkg/server/handler.go
> +	bindingKeySchemaSent       = "device.schema.sent"
```suggestion
	exchangeDevices            = "device"
	exchangeDevicesType        = "direct"
	exchangeDataSentType       = "fanout"
	exchangeDataSent           = "data.sent"
	queueNameCommands          = "babeltower-command-messages"
	queueNameEvents            = "babeltower-event-messages"
	bindingKeyAuthDevice       = "device.auth"
	bindingKeyListDevices      = "device.list"
	bindingKeyRegisterDevice   = "device.register"
	bindingKeyUnregisterDevice = "device.unregister"
	bindingKeyRequestData      = "data.request"
	bindingKeyUpdateData       = "data.update"
	bindingKeySchemaSent       = "device.schema.sent"
```

2020-05-07 13:33 UTC, netoax commented on pkg/server/handler.go
> +	subscribe(msgChan, queueNameEvents, exchangeDataSent, exchangeDataSentType, "")
Done. I found `bindingKeyEmpty` better.

2020-05-07 13:33 UTC, netoax commented on pkg/server/handler.go
> +	bindingKeySchemaSent       = "device.schema.sent"
Done.

2020-05-07 15:29 UTC, merged