thing: interactor: Adapt schema type rules
CESARBR/knot-babeltower pull request #85
Opened 2020-07-06 14:48 UTC by alla3

**Describe what this PR introduces:** (if necessary, link currently open issues with [special keywords](https://help.github.com/en/articles/closing-issues-using-keywords))

Adapt schema type rules to reflect the changes on commit
29523dd4d156473922ce55c09c14e9ac5c972269 from KNoT Protocol
repository (https://github.com/CESARBR/knot-protocol-source).

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug fix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce any breaking changes?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] Related issues are referenced in the PR (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included

**Testing environment:**

- Operating System/Platform:
- Go version:

If you have relevant logs, error output and etc, please attach them.

**Other information:**

2020-07-07 18:27 UTC, esdrasjnr requested changes
Looks great! :100: Just two comments:

- improve the commit message to make clear that the `valueType` is not associated with `typeId` anymore
- since this protocol change add some more value types, consider change the [data type checking](https://github.com/CESARBR/knot-babeltower/blob/b4a9de80f482495740733a5a0f71daf43a54201e/pkg/thing/interactors/update_data.go#L55) for `publishData` and `updateData` operations.

Thanks! :smile:

2020-07-08 19:28 UTC, netoax commented on pkg/thing/interactors/update_schema.go
> +	0x0000: {valueType: interval{1,7}, unit: 0},              // NONE
Which value types the interval 1-7 means?

2020-07-08 19:50 UTC, netoax commented on pkg/thing/interactors/update_schema.go
> +	0x0000: {valueType: interval{1,7}, unit: 0},              // NONE
I read your PR on the protocol repository and I got it. I'm updating this PR description to explicit it depends on that changes to be applied.

2020-07-12 01:45 UTC, esdrasjnr approved these changes
Excellent patch! Also, thanks for fixing the `float` typing check :100: 
Just consider improve the comments in `update_data.go` file by replacing the comments with `/* */` pattern! :+1:

2020-07-13 14:39 UTC, netoax requested changes
Very good, @alla3. Thanks for your contribution.
I made just one simple remark.

2020-07-13 14:39 UTC, netoax commented on pkg/thing/interactors/update_data.go
> +	case 1: /* int */
considering it's a single line comment:

```suggestion
	case 1: // int
```

2020-07-13 14:39 UTC, netoax commented on pkg/thing/interactors/update_data.go
> +	case 1: /* int */
same about the comments below.

2020-07-13 19:39 UTC, alla3 commented on pkg/thing/interactors/update_data.go
> +	case 1: /* int */
Done.

2020-07-14 11:07 UTC, netoax approved these changes
LGTM!

2020-07-24 14:37 UTC, merged